server:
  port: 8080
  nosql:
    document-base-package: "com.experience.mongo.repository"
spring:
  application:
    name: "DNA Mutant Search"
  data:
    mongodb:
      uri: "mongodb://admin:admin@3.212.189.37:27017/admin"
      auto-index-creation: false